"""Lightweight Reflect CLI (V3 P3-1).

Reflection mechanism for agents: after a session, an agent can submit
their reflections (key learnings, decisions, blockers) which become
candidate memories awaiting review.

The full Qoder-style reflect flow (with LLM-driven reflection) is
planned as a plugin-dependent enhancement. This implementation provides
the CLI surface and candidate creation so agents can already participate
in reflection manually.
"""

from __future__ import annotations

from datetime import datetime, timedelta, timezone

from flow_memory.storage import get_backend


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def submit_reflection(
    agent: str,
    learnings: list[dict],
    *,
    source_ref: str = "",
    evidence_refs: list[str] | None = None,
) -> list[str]:
    """Submit agent's reflection as candidate memories.

    Args:
        agent: agent name (e.g. "worker_course")
        learnings: list of {kind, content, proposed_scope, layer?, reason?}
        source_ref: optional reference (e.g. session id)
        evidence_refs: list of evidence refs

    Returns list of candidate_ids created.

    Each learning becomes a candidate with source_type="reflection" so
    reviewers can distinguish reflection-driven from event-driven.
    """
    if not learnings:
        raise ValueError("learnings cannot be empty")

    get_backend().init_schema()
    ids: list[str] = []
    for learning in learnings:
        kind = learning.get("kind", "note")
        content = learning.get("content", "").strip()
        if not content:
            continue
        scope = learning.get("proposed_scope", f"agent:{agent}")
        layer = learning.get("layer", "episode")
        reason = learning.get("reason", "")

        # Use add_candidate via memory_candidates module
        from flow_memory.candidates import add_candidate

        cid = add_candidate(
            scope=scope,
            kind=kind,
            content=content,
            source_type="reflection",
            source_ref=source_ref or f"reflect-{agent}-{_now_iso()[:10]}",
            layer=layer,
            reason=reason,
            evidence_refs=evidence_refs or [],
        )
        ids.append(cid)
    return ids


def list_recent_reflection_candidates(
    days: int = 7,
    limit: int = 50,
) -> list[dict]:
    """List candidates generated by reflection in the last N days."""
    get_backend().init_schema()
    cutoff = (datetime.now(timezone.utc) - timedelta(days=days)).isoformat()
    conn = get_backend().connect()
    rows = conn.execute(
        """SELECT * FROM memory_candidates
           WHERE source_type = 'reflection'
             AND created_at >= ?
           ORDER BY created_at DESC
           LIMIT ?""",
        (cutoff, limit),
    ).fetchall()
    return [dict(r) for r in rows]


def reflection_stats(days: int = 30) -> dict:
    """Statistics on reflection candidates: total, promoted, rejected."""
    get_backend().init_schema()
    cutoff = (datetime.now(timezone.utc) - timedelta(days=days)).isoformat()
    conn = get_backend().connect()
    rows = conn.execute(
        """SELECT review_status, COUNT(*) AS cnt
           FROM memory_candidates
           WHERE source_type = 'reflection'
             AND created_at >= ?
           GROUP BY review_status""",
        (cutoff,),
    ).fetchall()
    total = sum(row["cnt"] for row in rows)
    by_status = {row["review_status"]: row["cnt"] for row in rows}
    promoted = by_status.get("promoted", 0)
    promote_rate = promoted / total if total > 0 else 0.0
    return {
        "total": total,
        "by_status": by_status,
        "promote_rate": round(promote_rate, 3),
        "window_days": days,
    }
